# Generated by Django 5.2.1 on 2025-07-03 13:56

import cloudinary_storage.storage
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaRepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=usuarios.models.ruta_firma_representante, verbose_name='Firma del Representante Legal')),
                ('fecha_subida', models.DateTimeField()),
            ],
        ),
    ]
